#!/usr/bin/env python3
"""
Find items sorted by expiry date.

Reads best-before dates from inventory.json (generated by `inventory-md parse`).
Dates are expected in normalized YYYY-MM-DD format as produced by the parser.

Usage:
    ./find_expiring_items.py [inventory.json] [options]

Options:
    --food          Only show food items (requires vocabulary.json)
    --limit N       Show top N items sorted by expiry (no date filtering)
    --all           Show all items with expiry dates, not just expired ones
    --before DATE   Show items expiring before DATE (YYYY-MM-DD or YYYY-MM)
    -h, --help      Show this help message

By default (no options), shows only items that have already expired.

Examples:
    ./find_expiring_items.py                          # Show expired items only
    ./find_expiring_items.py --food                   # Expired food only
    ./find_expiring_items.py --limit 10               # Top 10 items by expiry date
    ./find_expiring_items.py --all                    # All items with expiry dates
    ./find_expiring_items.py --before 2026-06         # Items expiring before June 2026
    ./find_expiring_items.py ~/solveig-inventory/inventory.json
"""

import json
import sys
from datetime import date
from pathlib import Path


def _build_food_categories(vocab_path: Path) -> set[str] | None:
    """Return set of leaf category names that map to food/ concepts, or None if unavailable."""
    if not vocab_path.exists():
        return None
    try:
        with open(vocab_path) as f:
            vocab = json.load(f)
    except (OSError, json.JSONDecodeError):
        return None

    return {
        concept_id.split("/")[-1]
        for concept_id in vocab.get("concepts", {})
        if concept_id.startswith("food/") and not concept_id.startswith("category_by_source/")
    }


def find_expiring_items(inventory_path: Path, food_only: bool = False) -> list:
    """
    Find items with expiry dates, sorted oldest-first.

    Returns list of dicts with: id, name, container, parent, location, bb, days, expired, inferred
    """
    with open(inventory_path) as f:
        data = json.load(f)

    food_categories = _build_food_categories(inventory_path.parent / "vocabulary.json") if food_only else None
    today = date.today()
    items = []

    for container in data["containers"]:
        container_id = container.get("id", "unknown")
        parent_id = container.get("parent", "")

        for item in container.get("items", []):
            meta = item.get("metadata", {})

            if food_only:
                tags = meta.get("tags", [])
                categories = meta.get("categories", [])
                is_food = any(t.startswith("food/") for t in tags)
                if not is_food:
                    if food_categories is not None:
                        is_food = any(c in food_categories for c in categories)
                    else:
                        is_food = bool(categories)
                if not is_food:
                    continue

            bb = meta.get("bb")
            if not bb:
                continue

            try:
                exp_date = date.fromisoformat(bb)
            except ValueError:
                continue

            days_until = (exp_date - today).days
            location = f"{container_id}, {parent_id}" if parent_id else container_id

            items.append(
                {
                    "id": item.get("id") or (item.get("name") or "unknown")[:20],
                    "name": item.get("name", ""),
                    "container": container_id,
                    "parent": parent_id,
                    "location": location,
                    "bb": bb,
                    "days": days_until,
                    "expired": days_until < 0,
                    "inferred": meta.get("bb_inferred", False),
                }
            )

    items.sort(key=lambda x: x["days"])
    return items


def main():
    food_only = False
    limit = None
    before_date = None
    show_all = False
    inventory_path = Path("inventory.json")

    args = sys.argv[1:]
    while args:
        arg = args.pop(0)
        if arg in ("-h", "--help"):
            print(__doc__)
            sys.exit(0)
        elif arg == "--food":
            food_only = True
        elif arg == "--limit" and args:
            limit = int(args.pop(0))
        elif arg == "--before" and args:
            before_date = args.pop(0)
        elif arg == "--all":
            show_all = True
        elif not arg.startswith("-"):
            inventory_path = Path(arg)

    if not inventory_path.exists():
        print(f"Error: {inventory_path} not found", file=sys.stderr)
        print("Run: inventory-md parse inventory.md", file=sys.stderr)
        sys.exit(1)

    items = find_expiring_items(inventory_path, food_only=food_only)

    if before_date:
        if len(before_date) == 7:
            before_date += "-01"
        cutoff = date.fromisoformat(before_date)
        items = [i for i in items if date.fromisoformat(i["bb"]) < cutoff]
    elif limit is not None:
        items = items[:limit]
    elif not show_all:
        items = [i for i in items if i["expired"]]

    if not items:
        print("No matching items found.")
        sys.exit(0)

    print("Items to use/check first (by expiry date):")
    print()

    for item in items:
        inferred_marker = " ~EST" if item["inferred"] else ""
        if item["expired"]:
            status = f"EXPIRED {-item['days']}d ago"
        elif item["days"] <= 30:
            status = f"{item['days']}d left ⚠️"
        else:
            status = f"{item['days']}d left"

        name = item["name"][:45] if len(item["name"]) > 45 else item["name"]
        print(f"  {item['id']}")
        print(f"    {name}")
        print(f"    Location: {item['location']}")
        print(f"    Expires: {item['bb']}{inferred_marker} [{status}]")
        print()


if __name__ == "__main__":
    main()
